version: "3.8"
services:
  app:
    build:
      dockerfile: ./docker/local/Dockerfile
      context: .
      target: debugger
    environment:
      - APP_ENV=local
      - DB_NAME=example
      - DB_USER=test
      - DB_PASSWORD=password
      - DB_HOST=db
      - DB_PORT=3306
      - LOG_LEVEL=debug
    env_file: .env
    ports:
      - 80:8080
      - 2345:2345
    volumes:
      - .:/go/src/github.com/take0fit/shift-and-reservation
    depends_on:
      - db

  db:
    image: mysql:8.0
    volumes:
      - db:/var/lib/mysql
    tmpfs:
      - /var/lib/mysql,mode=755
      - /var/log/mysql,mode=755
    environment:
      - MYSQL_DATABASE=example
      - MYSQL_USER=test
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - 3306:3306

networks:
  backend:

volumes:
  db:
