// DO NOT EDIT! Code generated by openapi-generator
package schema

type ReservationSummary struct {

	// 予約ID
	ReservationId int32 `json:"reservationId"`

	// 予約開始日時
	StartTime string `json:"startTime"`

	// 予約終了日時
	EndTime string `json:"endTime"`

	// 複数メニューかフラグ
	IsMultipleMenu bool `json:"isMultipleMenu"`

	// 合計金額
	TotalPrice int32 `json:"totalPrice"`

	// 合計施術所要時間(分単位)
	TotalTreatmentTime int32 `json:"totalTreatmentTime"`

	User ReservationUserSummary `json:"user"`

	Menu ReservationMenuSummary `json:"menu"`

	WorkingSalon ReservationWorkingSalonSummary `json:"workingSalon"`

	// 支払い可能かフラグ
	IsPayable bool `json:"isPayable"`
}
