// DO NOT EDIT! Code generated by openapi-generator
package schema

// ResponseOneWeekShifts - 一週間分のシフト一覧
type ResponseOneWeekShifts struct {

	OneWeekShifts []OneWeekShift `json:"oneWeekShifts,omitempty"`

	// 最早予約可能時間
	OpeningTime string `json:"openingTime"`

	// 最遅予約可能時間
	ClosingTime string `json:"closingTime"`
}
