// DO NOT EDIT! Code generated by openapi-generator
package schema

// MenuSummaryForUser - メニュー情報
type MenuSummaryForUser struct {

	MenuId int32 `json:"menuId"`

	MenuName string `json:"menuName"`

	MenuPrice int32 `json:"menuPrice"`

	ImageUrl *string `json:"imageUrl"`
}
