// DO NOT EDIT! Code generated by openapi-generator
package schema

type ReservationUserSummary struct {

	// ビューティシャンID
	UserId int32 `json:"userId"`

	// ニックネーム
	Nickname string `json:"nickname"`

	// プロフィール画像URL
	ProfileImageUrl *string `json:"profileImageUrl"`
}
