// DO NOT EDIT! Code generated by openapi-generator
package schema

type Meta struct {

	// 1ページごとのデータ件数
	PerPage int32 `json:"perPage"`

	// 現在のページ番号
	CurrentPage int32 `json:"currentPage"`

	// 最後のページ番号
	LastPage int32 `json:"lastPage"`

	// データ総数
	Total int32 `json:"total"`
}
