// DO NOT EDIT! Code generated by openapi-generator
package schema

type ReservationMenu struct {

	// メニューID
	MenuId int32 `json:"menuId"`

	// メニュー名
	MenuName string `json:"menuName"`

	// メニューカテゴリ名
	MenuCategoryName string `json:"menuCategoryName"`

	// メニュー説明
	Explanation string `json:"explanation"`

	// 料金
	MenuPrice int32 `json:"menuPrice"`

	// 施術時間(分単位)
	TreatmentTime int32 `json:"treatmentTime"`

	// タグリスト
	Tags []string `json:"tags"`
}
