// DO NOT EDIT! Code generated by openapi-generator
package schema

type Reservation struct {

	// 予約ID
	ReservationId int32 `json:"reservationId"`

	// 予約開始日時
	StartTime string `json:"startTime"`

	// 予約終了日時
	EndTime string `json:"endTime"`

	Menus []ReservationMenu `json:"menus"`

	User ReservationUser `json:"user"`

	WorkingSalon ReservationWorkingSalon `json:"workingSalon"`

	Occupation ReservationOccupation `json:"occupation"`
}
