// DO NOT EDIT! Code generated by openapi-generator
package schema

// OneWeekShift - 一週間分のシフト
type OneWeekShift struct {

	// 日付
	Date string `json:"date"`

	NonReservableHours []Time `json:"nonReservableHours"`
}
