// DO NOT EDIT! Code generated by openapi-generator
package schema

// MenuForUserIndex - メニュー情報(ユーザー一覧のメニュー一覧で使用)
type MenuForUserIndex struct {

	MenuId int32 `json:"menuId"`

	MenuName string `json:"menuName"`

	MenuCategoryName string `json:"menuCategoryName"`

	Explanation *string `json:"explanation"`

	MenuPrice int32 `json:"menuPrice"`

	TreatmentTime int32 `json:"treatmentTime"`

	ImageUrl *string `json:"imageUrl"`
}
