// DO NOT EDIT! Code generated by openapi-generator
package schema

type ReservationWorkingSalonSummary struct {

	// 働いているサロンID
	WorkingSalonId int32 `json:"workingSalonId"`

	// 働いているサロン名
	WorkingSalonName string `json:"workingSalonName"`
}
