// DO NOT EDIT! Code generated by openapi-generator
package schema

// AreaForUser - エリア情報
type AreaForUser struct {

	// エリアID
	AreaId int32 `json:"areaId"`

	// エリア名
	AreaName string `json:"areaName"`
}
