// DO NOT EDIT! Code generated by openapi-generator
package schema

type OccupationSummary struct {

	OccupationId int32 `json:"occupationId"`

	OccupationName string `json:"occupationName"`

	OccupationYears int32 `json:"occupationYears"`
}
