// DO NOT EDIT! Code generated by openapi-generator
package schema

type ReservationOccupation struct {

	// 職種ID
	OccupationId int32 `json:"occupationId,omitempty"`

	// 職種名
	OccupationName string `json:"occupationName,omitempty"`

	// 職歴年数（年単位）
	Years int32 `json:"years,omitempty"`
}
