// DO NOT EDIT! Code generated by openapi-generator
package schema

type ReservationWorkingSalon struct {

	// 働いているサロンID
	WorkingSalonId int32 `json:"workingSalonId"`

	// 働いているサロン名
	WorkingSalonName string `json:"workingSalonName"`

	// 都道府県ID
	PrefectureId int32 `json:"prefectureId"`

	// 市町村
	City string `json:"city"`

	// 以降の住所
	Address string `json:"address"`

	// 最寄駅
	NearestStation string `json:"nearestStation"`

	// 緯度
	Latitude float64 `json:"latitude"`

	// 緯度
	Longitude float64 `json:"longitude"`
}
